version: "3"

services:
  feed_service:
    build:
      context: .
      dockerfile: Dockerfile
    image: feed-service-go
    container_name: feed-service-go
    ports:
      - 7454:7454
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    environment:
      - HOST=
      - PORT=
    restart: always
    command: >
      /go/bin/app
